/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LegalServicesRouteImport } from './routes/legal-services'
import { Route as LegalTeamRouteImport } from './routes/legal-team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertyDisclaimerRouteImport } from './routes/property-disclaimer'
import { Route as PropertyManagementRouteImport } from './routes/property-management'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantLoginRouteImport } from './routes/merchant.login'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties/$id'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalServicesRoute = LegalServicesRouteImport.update({
  id: '/legal-services',
  path: '/legal-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTeamRoute = LegalTeamRouteImport.update({
  id: '/legal-team',
  path: '/legal-team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyDisclaimerRoute = PropertyDisclaimerRouteImport.update({
  id: '/property-disclaimer',
  path: '/property-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-services': typeof LegalServicesRoute
  '/legal-team': typeof LegalTeamRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-disclaimer': typeof PropertyDisclaimerRoute
  '/property-management': typeof PropertyManagementRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/blog/': typeof BlogIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-services': typeof LegalServicesRoute
  '/legal-team': typeof LegalTeamRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-disclaimer': typeof PropertyDisclaimerRoute
  '/property-management': typeof PropertyManagementRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/blog': typeof BlogIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/favourites': typeof FavouritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-services': typeof LegalServicesRoute
  '/legal-team': typeof LegalTeamRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-disclaimer': typeof PropertyDisclaimerRoute
  '/property-management': typeof PropertyManagementRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/blog/': typeof BlogIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/favourites'
    | '/forgot-password'
    | '/legal-services'
    | '/legal-team'
    | '/login'
    | '/plans'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/property-disclaimer'
    | '/property-management'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sell'
    | '/terms'
    | '/blog/$slug'
    | '/merchant/login'
    | '/properties/$id'
    | '/properties/$propertyId'
    | '/blog/'
    | '/merchant/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/favourites'
    | '/forgot-password'
    | '/legal-services'
    | '/legal-team'
    | '/login'
    | '/plans'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/property-disclaimer'
    | '/property-management'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sell'
    | '/terms'
    | '/blog/$slug'
    | '/merchant/login'
    | '/properties/$id'
    | '/properties/$propertyId'
    | '/blog'
    | '/merchant'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/buy'
    | '/contact'
    | '/dashboard'
    | '/favourites'
    | '/forgot-password'
    | '/legal-services'
    | '/legal-team'
    | '/login'
    | '/plans'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/property-disclaimer'
    | '/property-management'
    | '/register'
    | '/rent'
    | '/reset-password'
    | '/sell'
    | '/terms'
    | '/blog/$slug'
    | '/merchant/login'
    | '/properties/$id'
    | '/properties/$propertyId'
    | '/blog/'
    | '/merchant/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FavouritesRoute: typeof FavouritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalServicesRoute: typeof LegalServicesRoute
  LegalTeamRoute: typeof LegalTeamRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertyDisclaimerRoute: typeof PropertyDisclaimerRoute
  PropertyManagementRoute: typeof PropertyManagementRoute
  RegisterRoute: typeof RegisterRoute
  RentRoute: typeof RentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-services': {
      id: '/legal-services'
      path: '/legal-services'
      fullPath: '/legal-services'
      preLoaderRoute: typeof LegalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-team': {
      id: '/legal-team'
      path: '/legal-team'
      fullPath: '/legal-team'
      preLoaderRoute: typeof LegalTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-disclaimer': {
      id: '/property-disclaimer'
      path: '/property-disclaimer'
      fullPath: '/property-disclaimer'
      preLoaderRoute: typeof PropertyDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FavouritesRoute: FavouritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalServicesRoute: LegalServicesRoute,
  LegalTeamRoute: LegalTeamRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertyDisclaimerRoute: PropertyDisclaimerRoute,
  PropertyManagementRoute: PropertyManagementRoute,
  RegisterRoute: RegisterRoute,
  RentRoute: RentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
